version: '3.9'

services:
  mongo:
    image: mongo:5.0.8
    container_name: mongodb
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin 
       MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always 

  api:
    build:
      context: .
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./application:/app/application
    environment:
      - FLASK_ENV=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=admin
      - MONGOPRD_USER=admin
      - MONGOPRD_PASSWORD=uMnyFW7eG2CgecZV
      - MONGOPRD_HOST=cluster0.bwf4i.mongodb.net
      - MONGOPRD_DB =users
    