name: Deploy Railway

on:
  push:
    branches: [ main ] 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4

      - name: install depedencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest 

      - name: Run tests
        run: make railway
        env:
          TOKEN_GIT: ${{ secrets.TOKEN_GIT }}
      
